export const AuthBJJCredentialHash      = 'ca938857241db9451ea329256b9c06e5';
export const AuthBJJCredentialURL       = 'https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/auth.json-ld';
export const AuthBJJCredential          = 'AuthBJJCredential';
export const Iden3CredentialSchemaURL   = 'https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/iden3credential.json-ld';
// Tempory
export const Iden3CredentialSchemaURLV2 = 'https://gist.githubusercontent.com/ilya-korotya/0d917c398f16e04817649d547eae620e/raw/577516d385bfe61a15d84cea71ec2584a9ac8a30/test.json-ld'
export const W3CCredentialSchemaURL2018 = 'https://www.w3.org/2018/credentials/v1';
export const Iden3Credential            = 'Iden3Credential';
export const W3CVerifiableCredential    = 'VerifiableCredential';
export const AuthBJJCredentialSchemaJSON = `{"$schema":"http://json-schema.org/draft-07/schema#","$metadata":{"uris":{"jsonLdContext":"https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/auth-v2.json-ld","jsonSchema":"https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json/auth-v1.json"},"serialization":{"indexDataSlotA":"x","indexDataSlotB":"y"}},"type":"object","required":["@context","id","type","issuanceDate","credentialSubject","credentialSchema","credentialStatus","issuer"],"properties":{"@context":{"type":["string","array","object"]},"id":{"type":"string"},"type":{"type":["string","array"],"items":{"type":"string"}},"issuer":{"type":["string","object"],"format":"uri","required":["id"],"properties":{"id":{"type":"string","format":"uri"}}},"issuanceDate":{"type":"string","format":"date-time"},"expirationDate":{"type":"string","format":"date-time"},"credentialSchema":{"type":"object","required":["id","type"],"properties":{"id":{"type":"string","format":"uri"},"type":{"type":"string"}}},"subjectPosition":{"type":"string","enum":["none","index","value"]},"merklizationRootPosition":{"type":"string","enum":["none","index","value"]},"revNonce":{"type":"integer"},"version":{"type":"integer"},"updatable":{"type":"boolean"},"credentialSubject":{"type":"object","required":["x","y"],"properties":{"id":{"title":"Credential Subject ID","type":"string","format":"uri"},"x":{"type":"string"},"y":{"type":"string"}}}}}`
