export * from './identity';
export * from './credentials';
export * from './kms';
export * from './storage';
export * from './verifiable';
export * from './schema-processor';
export * from './proof';
export * from './iden3comm';
export * from './circuits';
export * from './iden3comm';
export * from './utils';
import * as core from '@iden3/js-iden3-core';
import * as jsonLDMerklizer from '@iden3/js-jsonld-merklization';
export { core };
export { jsonLDMerklizer };
